import type { Metadata } from "next";
import { IBM_Plex_Sans, Faculty_Glyphic } from "next/font/google";
import "./globals.css";

const mainFont = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-main",
});

const subFont = Faculty_Glyphic({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-logo",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mainFont.variable} ${subFont.variable}`}>
      <body
        className={`${mainFont.className} text-neutral-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
